  CREATE TABLE traffic.ARC_TNODE (ARC_ID INT, TNODE_ID INT, X_COORD VARCHAR(40), Y_COORD VARCHAR(40), STREET1 VARCHAR(255), STREET2 VARCHAR(255));

  CREATE TABLE traffic.ARC_TABLE (ARC_ID INT, SEG_ID INT, SEGMENT VARCHAR(255), LFN_ID BIGINT, LENGTH VARCHAR(40));

  CREATE TABLE traffic.ARC_NODES (ARC_ID INT, FNODE_ID BIGINT, TNODE_ID INT, COLUMN4 DOUBLE PRECISION, COLUMN5 DOUBLE PRECISION);

  CREATE TABLE traffic.ARC_LINK (LINK_ID VARCHAR(50), ARC_ID INT, FREQUENCY BIGINT);

  CREATE TABLE traffic.SEG_TNODE (SEG_ID INT, TNODE_ID INT, X_COORD VARCHAR(40), Y_COORD VARCHAR(40), STREET1 VARCHAR(255), STREET2 VARCHAR(255));

  CREATE TABLE traffic.SEG_TABLE (SEG_ID INT, SEGMENT VARCHAR(255), LFN_ID BIGINT, LENGTH VARCHAR(40));

  CREATE TABLE traffic.SEG_NODES (SEG_ID INT, FNODE_ID BIGINT, TNODE_ID INT);

  CREATE TABLE traffic.SEG_FNODE (SEG_ID INT, FNODE_ID BIGINT, X_COORD VARCHAR(40), Y_COORD VARCHAR(40), STREET1 VARCHAR(255), STREET2 VARCHAR(255));

  CREATE TABLE traffic.NODE_ATTRIBUTE (NODE_ATTRIBUTE_ID CHAR(10), NODE_ID CHAR(10), RELATED_LAYER_NAME VARCHAR(50), RELATED_FIELD_NAME VARCHAR(50), RELATED_VALUE VARCHAR(50), TS TIMESTAMP(0));

  CREATE TABLE traffic.NODE_ARTERY (NODE_ARTERY_ID CHAR(10), NODE_ID CHAR(10), ARTERYCODE smallint, TS TIMESTAMP(0));

  CREATE TABLE traffic.NODE (NODE_ID CHAR(10), LINK_ID VARCHAR(10), X_COORD DOUBLE PRECISION, Y_COORD DOUBLE PRECISION, TS TIMESTAMP(0));

  CREATE TABLE traffic.GEOMETRY (GEOM_CODE smallint DEFAULT 0, NO_LANES INT DEFAULT 0, LANECONFIG VARCHAR(50), COMMENT_ VARCHAR(50));

  CREATE TABLE traffic.ARC_FNODE (ARC_ID int, FNODE_ID int, X_COORD VARCHAR(40), Y_COORD VARCHAR(40), STREET1 VARCHAR(255), STREET2 VARCHAR(255))