owners = {
    "bluetooth_itsc_pull": ["gabe", "dave"],
    "collisions_replicator": ["natalie", "gabe", "maddy"],
    "congestion_aggregate_temp": ["natalie"],
    "congestion_aggregation": ["natalie", "gabe"],
    "congestion_refresh": ["natalie", "gabe"],
    "counts_replicator": ["natalie", "gabe", "maddy"],
    "ecocounter_check": ["gabe", "david", "dave"],
    "ecocounter_open_data": ["gabe", "dave"],
    "ecocounter_pull": ["gabe", "dave"],
    "eoy_table_create": ["natalie", "gabe"],
    "gcc_pull_layers": ["gabe", "natalie"],
    "here_dynamic_binning_agg": ["gabe", "dave"],
    "lake_shore_signal_timing_refresh": ["natalie", "gabe"],
    "log_cleanup": ["natalie", "gabe"],
    "miovision_alerts": ["gabe", "dave"],
    "miovision_check": ["david", "gabe", "dave"],
    "miovision_hardware": ["gabe", "dave"],
    "miovision_open_data": ["gabe", "dave"],
    "miovision_pull": ["gabe", "dave"],
    "monitor_db_size": ["gabe", "natalie"],
    "open_data_checks": ["gabe", "dave"],
    "pull_here": ["natalie"],
    "pull_here_path": ["natalie"],
    "queens_park_aggregation": ["natalie"],
    "rapidto_aggregation": ["natalie"],
    "replicator_table_check": ["gabe", "peter"],
    "rodars_pull": ["gabe", "dave"],
    "temp_bluetooth_check_readers": ["natalie", "gabe"],
    "traffic_signals_dag": ["natalie", "gabe"],
    "traffic_signal_pull": ["natalie"],
    "tti_aggregate": ["natalie"],
    "vds_check": ["gabe", "dave"],
    "vds_pull_vdsdata": ["gabe", "dave"],
    "vds_pull_vdsvehicledata": ["gabe", "dave"],
    "vz_google_sheets": ["natalie", "gabe"],
    "vz_map_checks": ["gabe", "dave"],
    "weather_pull": ["dave", "gabe"],
    "wys_check": ["david", "gabe"],
    "wys_monthly_summary": ["natalie", "gabe"],
    "wys_pull": ["gabe", "natalie"],
    "ksi_open_data": ["natalie", "david"],
    "gtfs_pull": ["gabe", "dave"]
}
