detector_sql = '''SELECT 
        c.divisionid,
        c.vdsid,
        upper(c.sourceid) AS detector_id,
        c.starttimestamputc,
        c.endtimestamputc,
        c.lanes,
        c.hasgpsunit,
        c.managementurl,
        c.description,
        c.fssdivisionid,
        c.fssid,
        c.rtmsfromzone,
        c.rtmstozone,
        c.detectortype,
        c.createdby,
        c.createdbystaffid,
        c.signalid,
        c.signaldivisionid,
        c.movement,
        e.entitytype,                  
        e.locationtimestamputc,        
        e.latitude,                    
        e.longitude,                   
        e.altitudemetersasl,           
        e.headingdegrees,              
        e.speedkmh,                    
        e.numsatellites,               
        e.dilutionofprecision,         
        e.mainroadid,                  
        e.crossroadid,                 
        e.secondcrossroadid,           
        e.mainroadname,                
        e.crossroadname,               
        e.secondcrossroadname,         
        e.streetnumber,                
        e.offsetdistancemeters,        
        e.offsetdirectiondegrees,      
        e.locationsource,              
        e.locationdescriptionoverwrite
    FROM vdsconfig AS c 
    JOIN EntityLocationLatest AS e ON 
        c.vdsid = e.entityid 
        AND c.divisionid = e.divisionid 
    ORDER BY c.vdsid'''