INSERT INTO gwolofs.rodars_new (
    divisionid, issueid, timestamputc, issuetype, description, priority,
    proposedstarttimestamputc, proposedendtimestamputc, earlyendtimestamputc, status, timeoption,
    locationindex, mainroadname, fromroadname, toroadname, direction, lanesaffected,
    streetnumber, locationtype, groupid, groupdescription, sourceid, starttimestamputc,
    endtimestamputc, kmpost, managementurl, cancellationstatus, closeissueonplannedendtime,
    plannedstartadvancenoticeseconds, plannedendadvancenoticeseconds,
    locationdescriptionoverwrite, startissueonplannedstarttime, startstatus,
    updateremindernoticeseconds
)
VALUES %s
ON CONFLICT (divisionid, issueid, locationindex)
DO UPDATE SET
timestamputc = excluded.timestamputc,
issuetype = excluded.issuetype,
description = excluded.description,
priority = excluded.priority,
proposedstarttimestamputc = excluded.proposedstarttimestamputc,
proposedendtimestamputc = excluded.proposedendtimestamputc,
earlyendtimestamputc = excluded.earlyendtimestamputc,
status = excluded.status,
timeoption = excluded.timeoption,
mainroadname = excluded.mainroadname,
fromroadname = excluded.fromroadname,
toroadname = excluded.toroadname,
direction = excluded.direction,
lanesaffected = excluded.lanesaffected,
streetnumber = excluded.streetnumber,
locationtype = excluded.locationtype,
groupid = excluded.groupid,
groupdescription = excluded.groupdescription,
sourceid = excluded.sourceid,
starttimestamputc = excluded.starttimestamputc,
endtimestamputc = excluded.endtimestamputc,
kmpost = excluded.kmpost,
managementurl = excluded.managementurl,
cancellationstatus = excluded.cancellationstatus,
closeissueonplannedendtime = excluded.closeissueonplannedendtime,
plannedstartadvancenoticeseconds = excluded.plannedstartadvancenoticeseconds,
plannedendadvancenoticeseconds = excluded.plannedendadvancenoticeseconds,
locationdescriptionoverwrite = excluded.locationdescriptionoverwrite,
startissueonplannedstarttime = excluded.startissueonplannedstarttime,
startstatus = excluded.startstatus,
updateremindernoticeseconds = excluded.updateremindernoticeseconds;
